# Generated by Django 3.2.13 on 2022-10-30 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
