# Generated by Django 3.2.13 on 2022-10-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesAPI', '0002_remove_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandcookie',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
