# Generated by Django 3.2.13 on 2022-11-25 19:08

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesAPI', '0002_delete_basketitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=fernet_fields.fields.EncryptedEmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=fernet_fields.fields.EncryptedCharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=fernet_fields.fields.EncryptedCharField(max_length=150),
        ),
    ]
