# Generated by Django 3.2.13 on 2022-11-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesAPI', '0003_auto_20221125_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookie',
            old_name='photo',
            new_name='photo_main_page',
        ),
        migrations.AddField(
            model_name='cookie',
            name='photo_detail',
            field=models.ImageField(default='a', upload_to='images/'),
            preserve_default=False,
        ),
    ]
