# Generated by Django 3.2.13 on 2022-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesAPI', '0004_auto_20221128_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
