# Generated by Django 3.2.13 on 2022-12-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookiesAPI', '0006_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='available',
        ),
    ]
